### ISSUE TITLE
[REQUEST] "ESP Zigbee NCP serial-to-IP proxy SDK" example project?

### ISSUE THREAD

**Issue by Hedda** [lhespress/zigpy-espzb#4]
@chshu (and @lhespress) not sure if should post a request here or official repo at https://github.com/espressif/esp-zigbee-sdk

Duplicate/cross-posting of https://github.com/espressif/esp-zigbee-sdk/issues/253

Feature request for "ESP Zigbee NCP serial proxy SDK" example similar to "Gateway Example" (Zigbee gateway with RCP firmware):

https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_gateway

So please consider making and maintaining an "ESP Zigbee NCP serial proxy SDK" example design to be used with [zigpy-espzb](https://github.com/lhespress/zigpy-espzb)

The example should demonstrate how to build an ESP Zigbee NCP serial proxy server. Using a Wi-Fi SoC such as ESP32, ESP32-C3 or ESP32-S3 running a serial-to-network proxy relay server service (similar to "ser2net") allowing for a remote socket connection, used in combination with an 802.15.4 SoC like ESP32-H2 or  ESP32-C6 running [ESP Zigbee NCP](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_ncp) to provide 802.15.4 radio via [ZNSP (Zigbee NCP Serial Protocol) interface](https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32h2/application.html).

That is, a software solution that would make the two hardware designs from the "[ESP Thread Boarder Router SDK](https://github.com/espressif/esp-thread-br)" project usable as a network-attached remote Zigbee Coordinator NCP adapter, and as such instead offer a UART-to-IP serial streaming tunneling proxy relay solution (i.e. a remote Serial Port over TCP/IP) that works the same way as [TubesZB’s Zigbee Gateways](https://github.com/tube0013/tube_gateways) and [ZigStar’s Zigbee Gateways](https://github.com/mercenaruss/zigstar_gateways) solutions, meaning that it would present Espressif Zigbee NCP with ZNSP (Zigbee NCP Serial Protocol) interface as a remote serial communication port that can be used with Home Assistant's ZHA integration (which depends on zigpy):

https://www.home-assistant.io/integrations/zha

Such solutions based on ESP32 are commonly also referred to "Serial to TCP Bridge" and Tasmota is also a popular choice for it:

https://tasmota.github.io/docs/Serial-to-TCP-Bridge/

That is, just offering a pass-through tunneling of the UART port using a "ser2net" type Serial-to-IP proxy solution for relay connection:

* ESP32-C6/ESP32-H2 with Zigbee NCP firmware <-> ESP32-S3 with Serial-to-IP Proxy Server <-> Home Assistant's ZHA integration.

Preferably announcing the proxy service on the network via Zeroconf for automatic network discovery which is supported inside ZHA:

https://www.home-assistant.io/integrations/zha#discovery-via-usb-or-zeroconf

Otherwise, the end-user has to manually configure IP address and TCP port for the socket so Zeroconf makes it very user-friendly:

https://www.home-assistant.io/integrations/zha#zigate-or-sonoff-zbbridge-devices

FYI, Zeroconf (Zero-configuration networking) in the ZHA integration in turn depends on the Zeroconf integration:

https://www.home-assistant.io/integrations/zeroconf/

PS: TubesZB Zigbee Gateways and ZigStar Zigbee Gateways solutions as just examples as there are many ESP32-based solutions for this which shows that there are real-world use cases for "ESP Zigbee NCP serial-to-IP proxy" type products:

* https://tubeszb.com/
  * https://github.com/tube0013/tube_gateways

* https://zig-star.com/projects/
  * https://github.com/mercenaruss/zigstar_gateways

* https://shop.codm.de/automation/zigbee/40/zigbee-cc2652p2-tcp-ethernet-coordinator

* https://gio-dot.github.io/Z-Bee-Duo/

* https://smlight.tech/
  * https://github.com/smlight-dev/

* https://github.com/cyijun/OpenZ3Gateway

* https://shop68536829.taobao.com/

**Comment by chshu** [comment]
Addressed here: https://github.com/espressif/esp-zigbee-sdk/issues/253#issuecomment-1955843989

**Comment by lhespress** [comment]
@Hedda Close this beacuse of it's duplicate/cross-posting of https://github.com/espressif/esp-zigbee-sdk/issues/253
